### ISSUE TITLE
Tor Support

### ISSUE THREAD

**Issue by petak33** [GamehunterKaan/AutoPWN-Suite#13]
I think tor option to hide your identity would be cool

**Comment by GamehunterKaan** [comment]
This tool is mostly designed for using inside an internal network. But might as well add Tor support for testing outside targets.

**Comment by GamehunterKaan** [comment]
#### After experimenting with the `--proxy` flag in nmap I found out that you can't specify a socks5 proxy.
![Screenshot_20220616_195741](https://user-images.githubusercontent.com/68380968/174126403-03117bd8-6976-4b47-a609-f6723ebeade0.png)

#### Then I tried to specify it as socks4 even though it is socks5.
![Screenshot_20220616_200015](https://user-images.githubusercontent.com/68380968/174126602-167c87b9-58fd-4426-86a8-8af1b1721a67.png)

#### At first that seemed to work but after running `nc` on port 80 I realized it is actually not working.
![Screenshot_20220616_195918](https://user-images.githubusercontent.com/68380968/174126709-dbf9cfce-1625-4b8c-af67-e548200bc6d0.png)

**There are also other issues with using nmap with proxy :** 
- ICMP ping can not be done to see if a host is alive, since ICMP is not TCP.
- OS fingerprinting based on features of the IP stack is not possible because nmap does not speak with the targets IP stack when using a proxy, but instead with the proxies IP stack. This is a theoretical limit you have with any kind of proxy protocol.
- Nmap can do only CONNECT and SOCKS4 and these protocols can do only TCP.
- [See more on this stackexchange thread.](https://security.stackexchange.com/questions/120708/nmap-through-proxy)

This issue will be closed since it is not possible to use nmap with tor without using any external programs like "proxychains". I might consider adding this feature when nmap allows the use of socks5.
